<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useI18n } from 'vue-i18n';
import { useAuth } from '@/lib/auth';
import api from '@/lib/axios';
import { apiErrorMessage } from '@/lib/apiError';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';

const router = useRouter();
const { t } = useI18n();
const { passwordNeedsChange, clearPasswordNeedsChange } = useAuth();

const currentPassword = ref('');
const newPassword = ref('');
const confirmPassword = ref('');
const error = ref('');
const loading = ref(false);

async function handleSubmit() {
  error.value = '';

  if (!currentPassword.value || !newPassword.value || !confirmPassword.value) {
    error.value = t('passwordForm.allFieldsRequired');
    return;
  }

  if (newPassword.value.length < 8) {
    error.value = t('passwordForm.tooShort');
    return;
  }

  if (newPassword.value !== confirmPassword.value) {
    error.value = t('passwordForm.mismatch');
    return;
  }

  loading.value = true;
  try {
    await api.put('/admin/password', {
      current_password: currentPassword.value,
      new_password: newPassword.value,
    });
    clearPasswordNeedsChange();
    router.push({ name: 'dashboard' });
  } catch (e) {
    error.value = apiErrorMessage(e);
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div class="flex min-h-full items-center justify-center p-4">
    <Card class="w-full max-w-md">
      <CardHeader>
        <CardTitle class="text-2xl">{{ t('changePassword.title') }}</CardTitle>
        <CardDescription v-if="passwordNeedsChange">
          {{ t('changePassword.autoGeneratedNotice') }}
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form class="space-y-4" @submit.prevent="handleSubmit">
          <div class="space-y-2">
            <label class="text-sm font-medium" for="current-password">{{
              t('changePassword.currentPassword')
            }}</label>
            <Input
              id="current-password"
              v-model="currentPassword"
              type="password"
              :placeholder="t('changePassword.currentPlaceholder')"
              autofocus
            />
          </div>
          <div class="space-y-2">
            <label class="text-sm font-medium" for="new-password">{{
              t('passwordForm.newPassword')
            }}</label>
            <Input
              id="new-password"
              v-model="newPassword"
              type="password"
              :placeholder="t('passwordForm.atLeast8')"
            />
          </div>
          <div class="space-y-2">
            <label class="text-sm font-medium" for="confirm-password">{{
              t('changePassword.confirmNew')
            }}</label>
            <Input
              id="confirm-password"
              v-model="confirmPassword"
              type="password"
              :placeholder="t('passwordForm.repeatNew')"
            />
          </div>
          <p v-if="error" class="text-sm text-destructive">{{ error }}</p>
          <Button type="submit" class="w-full" :disabled="loading">
            {{
              loading ? t('passwordForm.changing') : t('changePassword.title')
            }}
          </Button>
        </form>
      </CardContent>
    </Card>
  </div>
</template>
